version: "3"
services:
  postgres:
    container_name: logman-postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  rabbitmq:
#    container_name: loc8-base-rabbitmq
#    image: registry.gitlab.com/ssquared/ssquared/dockerhub/rabbitmq/rabbitmq:3.9.12
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      - RABBITMQ_USERNAME=admin
#      - RABBITMQ_PASSWORD=admin

#  redis:
#    container_name: loc8-base-redis
#    image: registry.gitlab.com/ssquared/ssquared/dockerhub/redis/redis:5.0.14
#    ports:
#      - 6379:6379
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes

  minio:
    container_name: logman-minio
    image: minio/minio:RELEASE.2023-01-25T00-19-54Z.fips
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      CONSOLE_ACCESS_KEY: minio
      CONSOLE_SECRET_KEY: minio123
      # Debugging
      # MINIO_HTTP_TRACE: /dev/stdout
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data: