app:
  security:
    jwt:
      expiration-ms: 7200000
      secret: dAm8#uba668aFMNbusp123231sfd34fss1723!%20220712
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      password: password
      username: postgres
      schema: app
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    enabled: true
    locations: migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}
    schemas: public

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
