name: Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build client
        run: |
          cd client
          yarn install
          yarn build
          ls

      - name: Push client docker image
        run: |
          cd client
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build . -t jeannoel74/logman-client
          docker push jeannoel74/logman-client
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17

      - name: Build server
        run: |
          mvn -version
          mvn -DskipTests=true clean install

      - name: Push server docker image
        run: |
          docker build . -t jeannoel74/logman-server
          docker push jeannoel74/logman-server
          
#      - name: Save build folder as artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: build
#          path: client/build
#
#      - name: Save dockerfile as artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Dockerfile
#          path: client/Dockerfile
#
#  publish-client-docker-image:
#    runs-on: ubuntu-latest
#    needs: [build-client]
#    steps:
#      - name: Build client
#        run: |
#          whoami
#          mkdir build
#          ls
#          chmod 777 build
#      - name: Download build folder
#        uses: actions/download-artifact@v3
#        with:
#          name: build
#          path: /build
#      - name: Download docekr file
#        uses: actions/download-artifact@v3
#        with:
#          name: Dockerfile
#      - name: Push docker image
#        run: |
#          ls
#          cd client
#          ls
#          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#          docker build . -t jeannoel74/logman-client
#          docker push jeannoel74/logman-client
        
  #build-server:
  #server: docker-image:
