name: Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build client
        run: |
          cd client
          yarn install
          yarn build
          ls
          
      - name: Deploy client image
        run: |
          cd client
          ls
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build . -t jeannoel74/logman-client
          docker push jeannoel74/logman-client
          
  #build-server:
  client-docker-image:
    runs-on: ubuntu-latest
    needs: [deploy-client]
    steps:
      - name: Go to build directory
        run: cd build
      - name: Build docker image
        run: docker build . -t jeannoel74/logman-client
      - name: Push docker image
        run: docker push jeannoel74/logman-client
  #server: docker-image:
